### ISSUE TITLE
Edge case

### ISSUE THREAD

**Issue by csaftoiu** [ttaubert/node-arraybuffer-slice#1]
Fails for:

```
var ab = new ArrayBuffer(10); 
new Uint8Array(ab.slice(-1000, 5))
```

This should give the slice from 0 to 5, not throw a RangeError. Check the description at http://www.khronos.org/registry/typedarray/specs/latest/#5 , it covers all the edge cases - I think my implementation https://stackoverflow.com/questions/21440050/arraybuffer-prototype-slice-shim-for-ie covers them all

**Comment by ttaubert** [comment]
This should actually return an empty slice with byteLength=0. Firefox and Chrome both implement that behavior.

**Comment by csaftoiu** [comment]
Hmm I don't think so. I just ran it now in the Chrome console, and got back `[0, 0, 0, 0, 0]`. Are you sure you ran the same code?

![image](https://cloud.githubusercontent.com/assets/43113/3147924/92619ccc-ea5a-11e3-8027-cbe8d73076c8.png)

**Comment by ttaubert** [comment]
Sorry, my bad. You're absolutely right.
